version: "3"
services:
  database:
    image: docker.io/library/postgres:17-alpine
    environment:
      PGPORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hunter2
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: hunter2
    links:
      - database
    ports:
      - "8000:8000"
volumes:
  data:
